spring:
  profiles:
    active: cat, EN, qa
guru:
  username: superuser
  password: dbpassword
  url: someurls

---
spring:
  profiles: dev
guru:
  username: devUser
  password: devPassword
  url: devUrls

---
spring:
  profiles: qa
guru:
  username: qaUser
  password: qaPassword
  url: qaUrls